"""empty message

Revision ID: 631921dcdb5
Revises: 2ee83eafa391
Create Date: 2014-12-26 16:27:20.851102

"""

# revision identifiers, used by Alembic.
revision = '631921dcdb5'
down_revision = '2ee83eafa391'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
